### ISSUE TITLE
Building wheel for ninja (pyproject.toml) did not run successfully.

### ISSUE THREAD

**Issue by AndreyVus** [app-generator/django-datta-able#31]
OS: Raspbian on raspberry Pi.
Python 3.9.2 (default, Mar 12 2021, 04:06:34)

sudo apt update
sudo apt install cmake ninja -y
cd django-datta-able
docker-compose up --build

output:
 > [ 5/10] RUN pip install --no-cache-dir -r requirements.txt:
#0 4.620 Collecting django (from -r requirements.txt (line 1))
#0 4.883   Downloading Django-4.2.3-py3-none-any.whl (8.0 MB)
#0 5.571      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 11.8 MB/s eta 0:00:00
#0 5.904 Collecting gunicorn (from -r requirements.txt (line 2))
#0 5.936   Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)MB 12.6 MB/s eta 0:00:00
#0 5.946      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 30.0 MB/s eta 0:00:00
#0 6.058 Collecting python-dotenv (from -r requirements.txt (line 3))
#0 6.086   Downloading python_dotenv-1.0.0-py3-none-any.whl (19 kB)
#0 6.207 Collecting whitenoise (from -r requirements.txt (line 4))
#0 6.236   Downloading whitenoise-6.5.0-py3-none-any.whl (19 kB)
#0 6.295 Collecting django-admin-datta==1.0.10 (from -r requirements.txt (line 5))
#0 6.327   Downloading django-admin-datta-1.0.10.tar.gz (3.3 MB)
#0 6.563      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 14.3 MB/s eta 0:00:00
#0 7.042   Preparing metadata (setup.py): started
#0 9.300   Preparing metadata (setup.py): finished with status 'done'
#0 9.369 Collecting django-dynamic-datatb==1.0.25 (from -r requirements.txt (line 11))
#0 9.399   Downloading django-dynamic-datatb-1.0.25.tar.gz (21 kB)
#0 9.445   Preparing metadata (setup.py): started
#0 11.69   Preparing metadata (setup.py): finished with status 'done'
#0 11.84 Collecting django-api-generator==1.0.17 (from -r requirements.txt (line 12))
#0 11.87   Downloading django-api-generator-1.0.17.tar.gz (10 kB)
#0 11.92   Preparing metadata (setup.py): started
#0 14.17   Preparing metadata (setup.py): finished with status 'done'
#0 14.39 Collecting djangorestframework (from django-dynamic-datatb==1.0.25->-r requirements.txt (line 11))
#0 14.42   Downloading djangorestframework-3.14.0-py3-none-any.whl (1.1 MB)
#0 14.51      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 12.4 MB/s eta 0:00:00
#0 15.44 Collecting pandas (from django-dynamic-datatb==1.0.25->-r requirements.txt (line 11))
#0 15.47   Downloading pandas-2.0.3.tar.gz (5.3 MB)
#0 15.89      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 12.6 MB/s eta 0:00:00
#0 18.36   Installing build dependencies: started
#0 107.1   Installing build dependencies: still running...
#0 202.9   Installing build dependencies: still running...
#0 263.0   Installing build dependencies: still running...
#0 323.2   Installing build dependencies: still running...
#0 397.1   Installing build dependencies: still running...
#0 471.2   Installing build dependencies: still running...
#0 552.8   Installing build dependencies: still running...
#0 639.9   Installing build dependencies: still running...
#0 659.2   Installing build dependencies: finished with status 'done'
#0 659.2   Getting requirements to build wheel: started
#0 749.5   Getting requirements to build wheel: still running...
#0 815.3   Getting requirements to build wheel: still running...
#0 887.7   Getting requirements to build wheel: still running...
#0 966.1   Getting requirements to build wheel: still running...
#0 1033.6   Getting requirements to build wheel: still running...
#0 1101.0   Getting requirements to build wheel: still running...
#0 1150.6   Getting requirements to build wheel: finished with status 'done'
#0 1150.6   Preparing metadata (pyproject.toml): started
#0 1156.1   Preparing metadata (pyproject.toml): finished with status 'done'
#0 1157.2 Collecting matplotlib (from django-dynamic-datatb==1.0.25->-r requirements.txt (line 11))
#0 1157.5   Downloading matplotlib-3.7.1.tar.gz (38.0 MB)
#0 1162.0      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.0/38.0 MB 8.0 MB/s eta 0:00:00
#0 1169.2   Installing build dependencies: started
#0 1186.4   Installing build dependencies: finished with status 'done'
#0 1186.4   Getting requirements to build wheel: started
#0 1189.6   Getting requirements to build wheel: finished with status 'done'
#0 1189.6   Installing backend dependencies: started
#0 1193.8   Installing backend dependencies: finished with status 'done'
#0 1193.8   Preparing metadata (pyproject.toml): started
#0 1196.9   Preparing metadata (pyproject.toml): finished with status 'done'
#0 1197.1 Collecting asgiref<4,>=3.6.0 (from django->-r requirements.txt (line 1))
#0 1197.1   Downloading asgiref-3.7.2-py3-none-any.whl (24 kB)
#0 1197.2 Collecting sqlparse>=0.3.1 (from django->-r requirements.txt (line 1))
#0 1197.2   Downloading sqlparse-0.4.4-py3-none-any.whl (41 kB)
#0 1197.3      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 kB 28.3 MB/s eta 0:00:00
#0 1197.3 Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.9/site-packages (from gunicorn->-r requirements.txt (line 2)) (58.1.0)
#0 1197.4 Collecting typing-extensions>=4 (from asgiref<4,>=3.6.0->django->-r requirements.txt (line 1))
#0 1197.5   Downloading typing_extensions-4.7.1-py3-none-any.whl (33 kB)
#0 1198.1 Collecting pytz (from djangorestframework->django-dynamic-datatb==1.0.25->-r requirements.txt (line 11))
#0 1198.1   Downloading pytz-2023.3-py2.py3-none-any.whl (502 kB)
#0 1198.2      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.3/502.3 kB 9.3 MB/s eta 0:00:00
#0 1198.7 Collecting contourpy>=1.0.1 (from matplotlib->django-dynamic-datatb==1.0.25->-r requirements.txt (line 11))
#0 1198.7   Downloading contourpy-1.1.0.tar.gz (13.4 MB)
#0 1200.3      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.4/13.4 MB 9.2 MB/s eta 0:00:00
#0 1201.2   Installing build dependencies: started
#0 1223.2   Installing build dependencies: finished with status 'error'
#0 1223.2   error: subprocess-exited-with-error
#0 1223.2
#0 1223.2   × pip subprocess to install build dependencies did not run successfully.
#0 1223.2   │ exit code: 1
#0 1223.2   ╰─> [45 lines of output]
#0 1223.2       Collecting meson[ninja]>=1.1.0
#0 1223.2         Downloading meson-1.1.1-py3-none-any.whl (918 kB)
#0 1223.2            ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 918.4/918.4 kB 4.5 MB/s eta 0:00:00
#0 1223.2       Collecting meson-python>=0.13.1
#0 1223.2         Downloading meson_python-0.13.2-py3-none-any.whl (79 kB)
#0 1223.2            ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 5.0 MB/s eta 0:00:00
#0 1223.2       Collecting pybind11>=2.10.4
#0 1223.2         Using cached pybind11-2.10.4-py3-none-any.whl (222 kB)
#0 1223.2       Collecting ninja>=1.8.2 (from meson[ninja]>=1.1.0)
#0 1223.2         Downloading ninja-1.11.1.tar.gz (27 kB)
#0 1223.2         Installing build dependencies: started
#0 1223.2         Installing build dependencies: finished with status 'done'
#0 1223.2         Getting requirements to build wheel: started
#0 1223.2         Getting requirements to build wheel: finished with status 'done'
#0 1223.2         Preparing metadata (pyproject.toml): started
#0 1223.2         Preparing metadata (pyproject.toml): finished with status 'done'
#0 1223.2       Collecting pyproject-metadata>=0.7.1 (from meson-python>=0.13.1)
#0 1223.2         Downloading pyproject_metadata-0.7.1-py3-none-any.whl (7.4 kB)
#0 1223.2       Collecting tomli>=1.0.0 (from meson-python>=0.13.1)
#0 1223.2         Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
#0 1223.2       Collecting packaging>=19.0 (from pyproject-metadata>=0.7.1->meson-python>=0.13.1)
#0 1223.2         Using cached packaging-23.1-py3-none-any.whl (48 kB)
#0 1223.2       Building wheels for collected packages: ninja
#0 1223.2         Building wheel for ninja (pyproject.toml): started
#0 1223.2         Building wheel for ninja (pyproject.toml): finished with status 'error'
#0 1223.2         error: subprocess-exited-with-error
#0 1223.2
#0 1223.2         × Building wheel for ninja (pyproject.toml) did not run successfully.
#0 1223.2         │ exit code: 1
#0 1223.2         ╰─> [9 lines of output]
#0 1223.2             Traceback (most recent call last):
#0 1223.2               File "/tmp/pip-build-env-miua2mz1/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
#0 1223.2                 cmkr = cmaker.CMaker(cmake_executable)
#0 1223.2               File "/tmp/pip-build-env-miua2mz1/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 148, in __init__
#0 1223.2                 self.cmake_version = get_cmake_version(self.cmake_executable)
#0 1223.2               File "/tmp/pip-build-env-miua2mz1/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 105, in get_cmake_version
#0 1223.2                 raise SKBuildError(msg) from err
#0 1223.2
#0 1223.2             Problem with the CMake installation, aborting build. CMake executable is cmake
#0 1223.2             [end of output]
#0 1223.2
#0 1223.2         note: This error originates from a subprocess, and is likely not a problem with pip.
#0 1223.2         ERROR: Failed building wheel for ninja
#0 1223.2       Failed to build ninja
#0 1223.2       ERROR: Could not build wheels for ninja, which is required to install pyproject.toml-based projects
#0 1223.2       [end of output]
#0 1223.2
#0 1223.2   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 1223.2 error: subprocess-exited-with-error
#0 1223.2
#0 1223.2 × pip subprocess to install build dependencies did not run successfully.
#0 1223.2 │ exit code: 1
#0 1223.2 ╰─> See above for output.
#0 1223.2
#0 1223.2 note: This error originates from a subprocess, and is likely not a problem with pip.
------
Dockerfile:12
--------------------
  10 |     # install python dependencies
  11 |     RUN pip install --upgrade pip
  12 | >>> RUN pip install --no-cache-dir -r requirements.txt
  13 |
  14 |     COPY . .
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
ERROR: Service 'appseed-app' failed to build : Build failed

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
